In [1]:
string = 'This is the first time i am coding in months'

In [2]:
string.split('i ')

['This is the first time ', 'am coding in months']

In [3]:
'The {} name is {}'.format("murderer's",'Awulemaawu')

"The murderer's name is Awulemaawu"

In [4]:
list = ['maa','naa','ama']

In [5]:
list.append('aku')

In [6]:
list

['maa', 'naa', 'ama', 'aku']

In [7]:
list[1]

'naa'

In [8]:
list[:2]

['maa', 'naa']

In [12]:
lst=[1,3,4,3,5,5,5,2,1,1,1,6,5,3,3,5,5,5]

In [20]:
map(lambda x:x%2==0,lst)

In [18]:
print(a)

In [11]:
list(map(lambda x:x**2,lst))

TypeError: 'list' object is not callable

In [21]:
def list_benefits():
    return [ "More organized code", 
            "More readable code", "Easier code reuse", "Allowing programmers to share and connect code together"]

In [28]:
def build_sentence(info):
    print(info + " is a benefit of functions!")

In [29]:
for x in list_benefits():
    build_sentence(x)

More organized code is a benefit of functions!
More readable code is a benefit of functions!
Easier code reuse is a benefit of functions!
Allowing programmers to share and connect code together is a benefit of functions!


In [8]:
class myclass:
    variable = 'ouch'
    
    def function(self):
        print('This a practice round')

In [9]:
instantiation = myclass()

In [10]:
instantiation.variable

'ouch'

In [13]:
instantiation.function()

This a practice round


In [16]:
instantiation1 = myclass()

In [17]:
instantiation1.variable = 'my yacht'

In [19]:
print(instantiation1.variable)

my yacht


We have a class defined for vehicles. Create two new vehicles called car1 and car2. Set car1 to be a red convertible worth $60,000.00 with a name of Fer, and car2 to be a blue van named Jump worth $10,000.00.

In [21]:
len('This a practice round')

21

In [22]:
import time

In [23]:
print(time.ctime())

Fri Jul  3 12:16:49 2020


In [5]:
name = 'Ayinde'
age = '26'

In [7]:
print("My name is {}, and I am {} years old".format(name,age))

My name is Ayinde, and I am 26 years old


In [10]:
list = [1,4,5,6,7,6,5,3,5,2,2,1,3,1,4,5]
freq = {}
for x in list:
    if x in freq:
        freq[x]+=1
    else:
        freq[x]=1
print(freq)

{1: 3, 4: 2, 5: 4, 6: 2, 7: 1, 3: 2, 2: 2}


In [11]:
i = 1

while i < 5:
    print('the number is {}'.format(i))
    i+=1

the number is 1
the number is 2
the number is 3
the number is 4


In [17]:
set(range(0,19))

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18}

In [18]:
list(range(0,5))

TypeError: 'list' object is not callable

In [20]:
list = [1,4,5,6,7,6,5,3,5,2,2,1,3,1,4,5]
out = []

for x in list:
    if x >=3:
        out.append(x)

print(set(out))

{3, 4, 5, 6, 7}


In [23]:
set([x for x in list if x>=3])

{3, 4, 5, 6, 7}

In [28]:
def squared(num):
    return num**2

In [31]:
squared(65)

4225

In [30]:
output

4225

In [12]:
num = [2,3,4,5,6]
lambda x:x**3,num

(<function __main__.<lambda>(x)>, [2, 3, 4, 5, 6])

In [11]:
print(output)

[<function <lambda> at 0x0000013A1D928E58>, [2, 3, 4, 5, 6]]


In [21]:
list(map(lambda x:x**2,num))

[4, 9, 16, 25, 36]

In [22]:
list(filter(lambda a:a%2==1,num))

[3, 5]

In [33]:
string = 'This is a practice python coding procedure'

In [34]:
string.upper()

'THIS IS A PRACTICE PYTHON CODING PROCEDURE'

In [37]:
string[:7]

'This is'

In [38]:
num.pop()

6

In [39]:
num

[2, 3, 4, 5]

In [42]:
if 's' in string:
    print('shout')

shout


In [43]:
unpack = [(1,2),(3,4),(5,6)]

In [44]:
for item in unpack:
    print(item[0])

1
3
5


In [45]:
for (a,b) in unpack:
    print(a)

1
3
5


In [62]:
 # Create a function that counts the number of times the word "dog" occurs in a string. Again ignore edge cases. **
def dogcounter(string):
    x=0
    for item in string.lower().split():
        if item == 'dog':
            x+=1
        elif item == 'dogs':
            x+=1
    return x

In [63]:
dogcounter("""IT'S LIKELY NO surprise to dog owners, but growing research suggests 
that man's best friend often acts more human than canine Dogs can read facial expressions,
communicate jealousy, display empathy, and even watch TV, studies have shown. 
They've picked up these people-like traits during their evolution from wolves to domesticated pets,
which occurred between 11,000 and 16,000 years ago, experts say.In particular, 
'paying attention to us, getting along with us, [and] tolerating us' has led to particular characteristics
that often mirror ours, says Laurie Santos, director of the Yale Comparative Cognition Laboratory. 
(Read more about how dogs evolved in National Geographic magazine.)
Here are a few of the latest studies showing the human side of our canine companions.""")

3

In [64]:
def dogcounter1(string):
    x=0
    for item in string.lower().split():
        if 'dog' in item:
            x+=1
    return x

In [66]:
dogcounter1("""IT'S LIKELY NO surprise to dog owners, but growing research suggests 
that man's best friend often acts more human than canine Dogs can read facial expressions,
communicate jealousy, display empathy, and even watch TV, studies have shown. 
They've picked up these people-like traits during their evolution from wolves to domesticated pets,
which occurred between 11,000 and 16,000 years ago, experts say.In particular, 
'paying attention to us, getting along with us, [and] tolerating us' has led to particular characteristics
that often mirror ours, says Laurie Santos, director of the Yale Comparative Cognition Laboratory. 
(Read more about how dogs evolved in National Geographic magazine.)
Here are a few of the latest studies showing the human side of our canine companions.""")

3

In [68]:
# Use lambda expressions and the filter() function to filter out words from a list that don't start with the letter 's'. For example:**

seq = ['soup','dog','salad','cat','great']

out = list(filter(lambda x:x[0]=='s',seq))

In [69]:
out

['soup', 'salad']

In [80]:
### Final Problem**You are driving a little too fast, and a police officer stops you. Write a function
  #to return one of 3 possible results: "No ticket", "Small ticket", or "Big Ticket". 
  #If your speed is 60 or less, the result is "No Ticket". If speed is between 61 
  #and 80 inclusive, the result is "Small Ticket". If speed is 81 or more, the result is "Big   
  #Ticket". Unless it is your birthday (encoded as a boolean value in the parameters of the function) 
  #on your birthday, your speed can be 5 higher in all cases. **   

def speedtest(speed,birthday):
    
        if (speed <=60) or (speed<=65 and birthday==True):
            print('No Ticket')
        elif (speed >=61 and speed <=80) or (speed>=66 and speed <=85 and birthday==True):
            print('Small Ticket')
        elif (speed>=81) or (speed>=86 and birthday==True):
            print('Big Ticket')
    

In [86]:
speedtest(speed=30,birthday=True)

No Ticket


In [1]:
def caught_speeding(speed, is_birthday):
    
    if is_birthday:
        speeding = speed - 5
    else:
        speeding = speed
    
    if speeding > 80:
        return 'Big Ticket'
    elif speeding > 60:
        return 'Small Ticket'
    else:
        return 'No Ticket'

In [2]:
import numpy as np

In [4]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [12]:
np.random.rand(2,2)

array([[0.34706175, 0.66458614],
       [0.24483797, 0.81648467]])

In [14]:
np.random.randn(2,3)

array([[-0.49418646,  2.18950162,  0.94440689],
       [-1.12919267, -0.41974486, -0.68134508]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.randint(1,10,7)

array([7, 2, 1, 6, 3, 6, 1])

In [21]:
arr = np.arange(25)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
lin = np.linspace(0,25)

In [26]:
lin

array([ 0.        ,  0.51020408,  1.02040816,  1.53061224,  2.04081633,
        2.55102041,  3.06122449,  3.57142857,  4.08163265,  4.59183673,
        5.10204082,  5.6122449 ,  6.12244898,  6.63265306,  7.14285714,
        7.65306122,  8.16326531,  8.67346939,  9.18367347,  9.69387755,
       10.20408163, 10.71428571, 11.2244898 , 11.73469388, 12.24489796,
       12.75510204, 13.26530612, 13.7755102 , 14.28571429, 14.79591837,
       15.30612245, 15.81632653, 16.32653061, 16.83673469, 17.34693878,
       17.85714286, 18.36734694, 18.87755102, 19.3877551 , 19.89795918,
       20.40816327, 20.91836735, 21.42857143, 21.93877551, 22.44897959,
       22.95918367, 23.46938776, 23.97959184, 24.48979592, 25.        ])

In [28]:
lin.reshape(10,5)

array([[ 0.        ,  0.51020408,  1.02040816,  1.53061224,  2.04081633],
       [ 2.55102041,  3.06122449,  3.57142857,  4.08163265,  4.59183673],
       [ 5.10204082,  5.6122449 ,  6.12244898,  6.63265306,  7.14285714],
       [ 7.65306122,  8.16326531,  8.67346939,  9.18367347,  9.69387755],
       [10.20408163, 10.71428571, 11.2244898 , 11.73469388, 12.24489796],
       [12.75510204, 13.26530612, 13.7755102 , 14.28571429, 14.79591837],
       [15.30612245, 15.81632653, 16.32653061, 16.83673469, 17.34693878],
       [17.85714286, 18.36734694, 18.87755102, 19.3877551 , 19.89795918],
       [20.40816327, 20.91836735, 21.42857143, 21.93877551, 22.44897959],
       [22.95918367, 23.46938776, 23.97959184, 24.48979592, 25.        ]])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
int = np.random.randint(0,10,7)

In [34]:
int.max()

9

In [35]:
int

array([2, 4, 5, 5, 9, 8, 8])

In [36]:
int.argmax()

4

In [37]:
arr1 = np.arange(0,11)

In [38]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
slice_of_arr1 = arr1[:5]

In [49]:
slice_of_arr1

array([0, 1, 2, 3, 4])

In [50]:
slice_of_arr1[:] = 1

In [51]:
arr1

array([ 1,  1,  1,  1,  1,  5,  6,  7,  8,  9, 10])

In [46]:
slice_of_arr1

1

In [52]:
mat = np.random.randint(1,50,9)

In [53]:
mat = mat.reshape(3,3)

In [54]:
mat

array([[47, 27, 22],
       [25,  1, 18],
       [33, 42,  2]])

In [55]:
mat[2][1]

42

In [56]:
mat[2,1]

42

In [57]:
mat[0:2,1:]

array([[27, 22],
       [ 1, 18]])

In [58]:
arr2 = np.arange(0,11)

In [59]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr2[arr2>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [61]:
arr_2d = np.arange(0,50).reshape(5,10)

In [62]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [64]:
arr_2d[1:4,6:9]

array([[16, 17, 18],
       [26, 27, 28],
       [36, 37, 38]])

In [66]:
arr_2d[arr_2d>15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])